### PR TITLE
Laravel 7 support #13

### PR DESCRIPTION
**Pull request by dotzero**

### CODE REVIEW

**Comment by ElForastero** [comment]
Hi. 👋

Thank you for the PR. I'll do my best to deal with these failed pipelines today.

**Comment by dotzero** [comment]
@ElForastero oh, thank you, it would be great.

**Comment by dotzero** [comment]
@ElForastero Hi 👋 
I've fixed dependencies issues.

**Comment by ElForastero** [comment]
> @ElForastero Hi 👋
> I've fixed dependencies issues.

Many thanks 🙏
Shame on me, but I really don't have much time now.

**Pull request merged**
