### PR TITLE
Adapt for laravel 6

### PR DESCRIPTION
**Pull request by AkibaWolf**

### CODE REVIEW

**Comment by ElForastero** [comment]
#8 Thanks for the PR.
I'll check it and merge ASAP. 👍

**Comment by ElForastero** [comment]
By the way, docs should be updated as well. 🤔
I think we should bump the major release and leave the comment about 5.x support in the current 2.x version.

**Comment by AkibaWolf** [comment]
My thoughts exactly)

**Comment by haemmid** [comment]
I apologize for the concern, can we expect an update in the near future? :)

**Comment by ElForastero** [comment]
Sorry for the delay in accepting the MR.
Done in #11

**Pull request closed without merging**
